AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  obtemcota

  Sample SAM Template for obtemcota

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mapreducemachine
    Description: mapreducemachine
    Author: Rafael Barriento
    HomePageUrl: https://github.com/OlhaNoMeuGitHub/obtemcota
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/OlhaNoMeuGitHub/obtemcota

Parameters:
    AMBIENTE: # Changed this to remove underscore
        Description: 'Ambiente'
        Type: 'String'
    APIKEY: # Changed this to remove underscore
        Description: 'api key'
        Type: 'String'
    APIURL: # Changed this to remove underscore
      Description: 'api url'
      Type: 'String'
    teste: # Changed this to remove underscore
      Description: 'api url'
      Type: 'String'
    bucketCotacoes: # Changed this to remove underscore
      Description: 'api url'
      Type: 'String'
    MAPBUCKET: # Changed this to remove underscore
      Description: 'api url'
      Type: 'String'
    REDUCEBUCKET: # Changed this to remove underscore
      Description: 'api url'
      Type: 'String'
    StateMachineURL: # Changed this to remove underscore
      Description: 'api url'
      Type: 'String'
    ENDPOINTHOST: # Changed this to remove underscore
      Description: 'api url'
      Type: 'String'


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        AMBIENTE: !Ref AMBIENTE
        API_KEY: !Ref APIKEY
        API_URL: !Ref APIURL
        bucketCotacoes: !Ref bucketCotacoes
        MAPBUCKET: !Ref MAPBUCKET
        REDUCEBUCKET: !Ref REDUCEBUCKET
        StateMachineURL: !Ref StateMachineURL
        ENDPOINTHOST: !Ref ENDPOINTHOST
    
Resources:

  MapReduceStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/statemachineMap.asl.json
      DefinitionSubstitutions:
        SplitCotacoesArn: !GetAtt SplitCotacoes.Arn
        MapCalculaIndicadoresArn: !GetAtt MapCalculaIndicadores.Arn
        ReduceIndicadoresArn: !GetAtt ReduceIndicadores.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref SplitCotacoes
        - LambdaInvokePolicy:
            FunctionName: !Ref MapCalculaIndicadores
        - LambdaInvokePolicy:
            FunctionName: !Ref ReduceIndicadores
      
  SplitCotacoes:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: SplitCotacoes/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  ObtemCotacao:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Obtem-cotacao/source/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables: 
          StateMachineURL: !GetAtt MapReduceStateMachine.Arn
      Architectures:
        - x86_64            

  Cotacaoyahoo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cotacaoyahoo/source/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables: 
          StateMachineURL: !GetAtt MapReduceStateMachine.Arn
      Architectures:
        - x86_64
  MapCalculaIndicadores:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: MapCalculaIndicadores/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  ReduceIndicadores:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ReduceIndicadores/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/obtemcotacao/"
  MapReduceStateMachineArn:
    Description: "Stock Trading state machine ARN"
    Value: !Ref MapReduceStateMachine
  MapReduceStateMachineIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt MapReduceStateMachineRole.Arn
